version: '3.7'

services:

  sample:
    container_name: sample-2
    tty: true
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 3001:3001
    command:
      - /app/boot.sh
