default: &default
  adapter: sqlite3
  encoding: unicode
  host: postgres
  username: postgres
  password: postgres
  pool: 5
development:
  <<: *default
  database: api_dev
test:
  <<: *default
  database: app_test
production:
  <<: *default
  database: <%= Rails.application.credentials.dig(:postgres, :database) %>
  host: <%= Rails.application.credentials.dig(:postgres, :host) %>
  username: <%= Rails.application.credentials.dig(:postgres, :username)%>
  password: <%= Rails.application.credentials.dig(:postgres, :password) %>
  pool: <%= Integer(ENV.fetch('DB_POOL'){ 10 }) %>
